CREATE TABLE IF NOT EXISTS conundrums  (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    text TEXT UNIQUE NOT NULL,
    tags TEXT NOT NULL,
    stars INTEGER NOT NULL DEFAULT 0,
    verified INTEGER NOT NULL DEFAULT 0
);
