name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: and-fm/cloudflared-ssh-action@v3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          private_key_value: ${{ secrets.SSH_PRIVATE_KEY_VALUE }}
          private_key_filename: ${{ secrets.SSH_PRIVATE_KEY_FILENAME }}
          commands: |
            cd ~/git/risuhunnik
            git pull origin main
            [ ! -f risuhunnik.db ] && sqlite3 risuhunnik.db < sql/dump.sql
            docker compose down
            docker compose up --build
